In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('train.csv')

In [3]:
test = pd.read_csv('test.csv')

In [4]:
train.shape

(24000, 25)

In [5]:
train.head

<bound method NDFrame.head of              client_id  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  \
0      CC_0000F52C3717      50000    2          1         2   26      1
1      CC_0008C4E44BB9     150000    2          1         2   26     -1
2      CC_000B4B1BEDF6     450000    2          2         1   38     -2
3      CC_000D492CE7AD     230000    2          2         2   30      0
4      CC_000DCFA992C4     160000    2          2         2   34     -1
...                ...        ...  ...        ...       ...  ...    ...
23995  CC_FFF7FD14A18A      20000    2          3         2   35     -2
23996  CC_FFF97318AFBF     200000    1          2         2   44     -1
23997  CC_FFFB28EA5580     250000    2          2         2   36     -1
23998  CC_FFFD3A829DD0      20000    2          2         2   35      0
23999  CC_FFFEDC33E37A     290000    1          2         2   26      0

       PAY_2  PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0          2      0      0  ...      39475      40187      40992      2200
1         -1     -1      0  ...      18400       1527       1527         0
2         -2     -2     -2  ...      17255      17515          0     15008
3          0      0      0  ...     108826     100862      92481      6000
4         -1     -1     -1  ...      13780      12297      12752     24000
...      ...    ...    ...  ...        ...        ...        ...       ...
23995     -2     -2     -2  ...          0          0          0      1492
23996     -1     -1      0  ...        541        541        541       541
23997     -1     -1     -1  ...       3160        396        396       396
23998      0      2      0  ...      19000      19000      20000      3400
23999      0      0      0  ...      51395      52332        416      2000

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default
0          1962      1562      1500      1474      2300        0
1         18600         0      1527         0         0        0
2          1200      5255      4566         0      3648        0
3          6000      4000      4000      3500      4000        0
4          8000     13780     12300     12752      6000        0
...         ...       ...       ...       ...       ...      ...
23995         0         0         0         0         0        0
23996      1082         0       541       541       541        0
23997       396      3160       396       396       396        0
23998         0      1000         0      1000         0        0
23999      2300      5000      2600         0       416        0

[24000 rows x 25 columns]>

In [6]:
train.isnull().sum()

client_id    0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
default      0
dtype: int64

In [7]:
train.duplicated().sum()

np.int64(0)

In [8]:
train["default"].value_counts(normalize=True)*100

default
0    77.879167
1    22.120833
Name: proportion, dtype: float64

In [9]:
x = train.drop(columns=["default"])
y = train["default"]
x_test = test.drop(columns=["client_id"])

In [10]:
x = x.drop(columns=["client_id"])

In [11]:
x.shape

(24000, 23)

In [12]:
print(train.info())

<class 'pandas.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  24000 non-null  str
 1   LIMIT_BAL  24000 non-null  int64
 2   SEX        24000 non-null  int64
 3   EDUCATION  24000 non-null  int64
 4   MARRIAGE   24000 non-null  int64
 5   AGE        24000 non-null  int64
 6   PAY_0      24000 non-null  int64
 7   PAY_2      24000 non-null  int64
 8   PAY_3      24000 non-null  int64
 9   PAY_4      24000 non-null  int64
 10  PAY_5      24000 non-null  int64
 11  PAY_6      24000 non-null  int64
 12  BILL_AMT1  24000 non-null  int64
 13  BILL_AMT2  24000 non-null  int64
 14  BILL_AMT3  24000 non-null  int64
 15  BILL_AMT4  24000 non-null  int64
 16  BILL_AMT5  24000 non-null  int64
 17  BILL_AMT6  24000 non-null  int64
 18  PAY_AMT1   24000 non-null  int64
 19  PAY_AMT2   24000 non-null  int64
 20  PAY_AMT3   24000 non-null  int64
 21  PAY_AMT4   24000 non-null  int64
 22  PAY_AMT5   24000 non-null  int64
 23  PAY_AMT6   24000 non-null  int64
 24  default    24000 non-null  int64
dtypes: int64(24), str(1)
memory usage: 4.9 MB
None

In [13]:
train.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default
count,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000,...,24000.000000,24000.000000,24000.000000,24000.000000,2.400000e+04,24000.000000,24000.000000,24000.000000,24000.000000,24000.000000
mean,167608.736667,1.601792,1.850708,1.547958,35.540708,-0.019875,-0.137042,-0.168542,-0.225000,-0.269667,...,43175.799292,40271.754333,38743.087125,5711.710125,5.955190e+03,5262.745792,4853.362792,4749.935125,5161.937458,0.221208
std,130130.702503,0.489539,0.795213,0.521898,9.255129,1.125514,1.199960,1.202787,1.172113,1.135635,...,64534.910992,60980.478739,59707.335820,17155.309436,2.435021e+04,18426.028570,15752.040523,14873.057360,17925.431411,0.415069
min,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-65167.000000,-61372.000000,-209051.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2300.750000,1710.250000,1206.000000,992.500000,7.800000e+02,390.000000,298.750000,212.750000,100.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,18932.000000,18021.500000,16926.500000,2100.000000,2.000000e+03,1800.000000,1500.000000,1500.000000,1500.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,42.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,54341.500000,49937.500000,48904.750000,5004.000000,5.000000e+03,4500.000000,4001.250000,4005.000000,4000.000000,0.000000
max,1000000.000000,2.000000,6.000000,3.000000,75.000000,8.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.000000,621000.000000,417990.000000,528666.000000,1.000000

In [14]:
for col in ["SEX", "EDUCATION", "MARRIAGE"]:
    print("\n", col)
    print(train[col].value_counts().sort_index())

 SEX
SEX
1     9557
2    14443
Name: count, dtype: int64

 EDUCATION
EDUCATION
0       10
1     8551
2    11151
3     3911
4       97
5      237
6       43
Name: count, dtype: int64

 MARRIAGE
MARRIAGE
0       42
1    11019
2    12685
3      254
Name: count, dtype: int64

In [15]:
for col in ["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]:
    print("\n", col)
    print(train[col].value_counts().sort_index())

 PAY_0
PAY_0
-2     2241
-1     4561
 0    11739
 1     2944
 2     2147
 3      262
 4       56
 5       18
 6       11
 7        6
 8       15
Name: count, dtype: int64

 PAY_2
PAY_2
-2     3061
-1     4848
 0    12543
 1       23
 2     3137
 3      261
 4       78
 5       23
 6        9
 7       16
 8        1
Name: count, dtype: int64

 PAY_3
PAY_3
-2     3322
-1     4747
 0    12540
 1        4
 2     3075
 3      187
 4       64
 5       18
 6       19
 7       21
 8        3
Name: count, dtype: int64

 PAY_4
PAY_4
-2     3538
-1     4547
 0    13096
 1        2
 2     2541
 3      144
 4       53
 5       28
 6        4
 7       45
 8        2
Name: count, dtype: int64

 PAY_5
PAY_5
-2     3688
-1     4425
 0    13503
 2     2111
 3      144
 4       65
 5       15
 6        4
 7       44
 8        1
Name: count, dtype: int64

 PAY_6
PAY_6
-2     3984
-1     4571
 0    12989
 2     2206
 3      143
 4       43
 5       11
 6       18
 7       34
 8        1
Name: count, dtype: int64

In [16]:
train.groupby("default")["LIMIT_BAL"].mean()

default
0    178055.855759
1    130828.344321
Name: LIMIT_BAL, dtype: float64

In [17]:
train.groupby("default")["AGE"].mean()

default
0    35.479857
1    35.754944
Name: AGE, dtype: float64

In [18]:
train.groupby("default")["PAY_0"].mean()

default
0   -0.214970
1    0.666981
Name: PAY_0, dtype: float64

In [19]:
cols = [
    "LIMIT_BAL",
    "AGE",
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

train.groupby("default")[cols].mean()

,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6
default,,,,,,,,
0,178055.855759,35.479857,-0.214970,-0.305655,-0.322294,-0.361297,-0.395591,-0.413087
1,130828.344321,35.754944,0.666981,0.456583,0.372763,0.254850,0.173667,0.113769

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

logistic_model.fit(x, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=1000))])

In [21]:
logistic_prob = logistic_model.predict_proba(x_test)[:, 1]

In [22]:
train_fe = train.copy()
bill_cols = [
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6"
]

train_fe["TOTAL_BILL"] = train_fe[bill_cols].sum(axis=1)

train_fe["AVG_BILL"] = train_fe[bill_cols].mean(axis = 1)

payment_cols = [
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]
train_fe["TOTAL_PAYMENT"] = train_fe[payment_cols].sum(axis=1)
train_fe["AVG_PAYMENT"] = train_fe[payment_cols].mean(axis=1)

In [23]:
for i in range(1, 7):
    train_fe[f"UTIL_{i}"] = (train_fe[f"BILL_AMT{i}"] / (train_fe["LIMIT_BAL"] +1))

util_cols = [f"UTIL_{i}" for i in range(1, 7)]

train_fe["AVG_UTIL"] = train_fe[util_cols].mean(axis=1)
train_fe["MAX_UTIL"] = train_fe[util_cols].max(axis=1)

print(train_fe)

             client_id  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  \
0      CC_0000F52C3717      50000    2          1         2   26      1
1      CC_0008C4E44BB9     150000    2          1         2   26     -1
2      CC_000B4B1BEDF6     450000    2          2         1   38     -2
3      CC_000D492CE7AD     230000    2          2         2   30      0
4      CC_000DCFA992C4     160000    2          2         2   34     -1
...                ...        ...  ...        ...       ...  ...    ...
23995  CC_FFF7FD14A18A      20000    2          3         2   35     -2
23996  CC_FFF97318AFBF     200000    1          2         2   44     -1
23997  CC_FFFB28EA5580     250000    2          2         2   36     -1
23998  CC_FFFD3A829DD0      20000    2          2         2   35      0
23999  CC_FFFEDC33E37A     290000    1          2         2   26      0

       PAY_2  PAY_3  PAY_4  ...  TOTAL_PAYMENT   AVG_PAYMENT    UTIL_1  \
0          2      0      0  ...          10998   1833.000000  0.844123
1         -1     -1      0  ...          20127   3354.500000  0.253678
2         -2     -2     -2  ...          29677   4946.166667  0.024382
3          0      0      0  ...          27500   4583.333333  0.488702
4         -1     -1     -1  ...          76832  12805.333333  0.118487
...      ...    ...    ...  ...            ...           ...       ...
23995     -2     -2     -2  ...           1492    248.666667  0.000000
23996     -1     -1      0  ...           3246    541.000000  0.002705
23997     -1     -1     -1  ...           5140    856.666667  0.001584
23998      0      2      0  ...           5400    900.000000  0.826359
23999      0      0      0  ...          12316   2052.666667  0.158762

         UTIL_2    UTIL_3    UTIL_4    UTIL_5    UTIL_6  AVG_UTIL  MAX_UTIL
0      0.844503  0.777164  0.789484  0.803724  0.819824  0.813137  0.844503
1      0.000000  0.123999  0.122666  0.010180  0.010180  0.086784  0.253678
2      0.033344  0.030860  0.038344  0.038922  0.000000  0.027642  0.038922
3      0.505533  0.515072  0.473154  0.438529  0.402090  0.470513  0.515072
4      0.074012  0.049487  0.086124  0.076856  0.079700  0.080778  0.118487
...         ...       ...       ...       ...       ...       ...       ...
23995  0.074596  0.000000  0.000000  0.000000  0.000000  0.012433  0.074596
23996  0.002705  0.005410  0.002705  0.002705  0.002705  0.003156  0.005410
23997  0.001584  0.001584  0.012640  0.001584  0.001584  0.003427  0.012640
23998  0.967302  0.929954  0.949953  0.949953  0.999950  0.937245  0.999950
23999  0.162203  0.165679  0.177224  0.180455  0.001434  0.140959  0.180455

[24000 rows x 37 columns]

In [24]:
for i in range(1, 7):
    train_fe[f"PAY_RATIO_{i}"] = (
        train_fe[f"PAY_AMT{i}"] /
        (train_fe[f"BILL_AMT{i}"].abs() + 1))

ratio_cols = [f"PAY_RATIO_{i}" for i in range(1, 7)]
train_fe["AVG_PAY_RATIO"] = train_fe[ratio_cols].mean(axis=1)

print(train_fe)

             client_id  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  \
0      CC_0000F52C3717      50000    2          1         2   26      1
1      CC_0008C4E44BB9     150000    2          1         2   26     -1
2      CC_000B4B1BEDF6     450000    2          2         1   38     -2
3      CC_000D492CE7AD     230000    2          2         2   30      0
4      CC_000DCFA992C4     160000    2          2         2   34     -1
...                ...        ...  ...        ...       ...  ...    ...
23995  CC_FFF7FD14A18A      20000    2          3         2   35     -2
23996  CC_FFF97318AFBF     200000    1          2         2   44     -1
23997  CC_FFFB28EA5580     250000    2          2         2   36     -1
23998  CC_FFFD3A829DD0      20000    2          2         2   35      0
23999  CC_FFFEDC33E37A     290000    1          2         2   26      0

       PAY_2  PAY_3  PAY_4  ...    UTIL_6  AVG_UTIL  MAX_UTIL  PAY_RATIO_1  \
0          2      0      0  ...  0.819824  0.813137  0.844503     0.052123
1         -1     -1      0  ...  0.010180  0.086784  0.253678     0.000000
2         -2     -2     -2  ...  0.000000  0.027642  0.038922     1.367721
3          0      0      0  ...  0.402090  0.470513  0.515072     0.053379
4         -1     -1     -1  ...  0.079700  0.080778  0.118487     1.265890
...      ...    ...    ...  ...       ...       ...       ...          ...
23995     -2     -2     -2  ...  0.000000  0.012433  0.074596  1492.000000
23996     -1     -1      0  ...  0.002705  0.003156  0.005410     0.998155
23997     -1     -1     -1  ...  0.001584  0.003427  0.012640     0.997481
23998      0      2      0  ...  0.999950  0.937245  0.999950     0.205699
23999      0      0      0  ...  0.001434  0.140959  0.180455     0.043439

        PAY_RATIO_2  PAY_RATIO_3  PAY_RATIO_4  PAY_RATIO_5  PAY_RATIO_6  \
0          0.046463     0.040196     0.037998     0.036678     0.056107
1      18600.000000     0.000000     0.082985     0.000000     0.000000
2          0.079968     0.378384     0.264604     0.000000  3648.000000
3          0.051602     0.033764     0.036756     0.034701     0.043252
4          0.675505     1.740119     0.892533     1.036917     0.470478
...             ...          ...          ...          ...          ...
23995      0.000000     0.000000     0.000000     0.000000     0.000000
23996      1.996310     0.000000     0.998155     0.998155     0.998155
23997      0.997481     7.959698     0.125277     0.997481     0.997481
23998      0.000000     0.053761     0.000000     0.052629     0.000000
23999      0.048895     0.104063     0.050588     0.000000     0.997602

       AVG_PAY_RATIO
0           0.044927
1        3100.013831
2         608.348446
3           0.042242
4           1.013573
...              ...
23995     248.666667
23996       0.998155
23997       2.012483
23998       0.052015
23999       0.207431

[24000 rows x 44 columns]

In [25]:
pay_status_cols = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

In [26]:
train_fe["AVG_PAY_STATUS"] = (
    train_fe[pay_status_cols].mean(axis=1)
)

In [27]:
train_fe["MAX_PAY_STATUS"] = (
    train_fe[pay_status_cols].max(axis=1)
)

In [28]:
train_fe["NUM_DELAY"] = (
    train_fe[pay_status_cols] > 0
).sum(axis=1)

In [29]:
x_fe = train_fe.drop(
    columns=["default", "client_id"]
)

y_fe = train_fe["default"]

In [33]:
test_fe = test.copy()

In [36]:
bill_cols = [
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3",
    "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"
]

test_fe["TOTAL_BILL"] = test_fe[bill_cols].sum(axis=1)
test_fe["AVG_BILL"] = test_fe[bill_cols].mean(axis=1)

payment_cols = [
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3",
    "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"
]

test_fe["TOTAL_PAYMENT"] = test_fe[payment_cols].sum(axis=1)
test_fe["AVG_PAYMENT"] = test_fe[payment_cols].mean(axis=1)

for i in range(1, 7):
    test_fe[f"UTIL_{i}"] = (
        test_fe[f"BILL_AMT{i}"] /
        (test_fe["LIMIT_BAL"] + 1)
    )

util_cols = [f"UTIL_{i}" for i in range(1, 7)]

test_fe["AVG_UTIL"] = test_fe[util_cols].mean(axis=1)
test_fe["MAX_UTIL"] = test_fe[util_cols].max(axis=1)

for i in range(1, 7):
    test_fe[f"PAY_RATIO_{i}"] = (
        test_fe[f"PAY_AMT{i}"] /
        (test_fe[f"BILL_AMT{i}"].abs() + 1)
    )

ratio_cols = [f"PAY_RATIO_{i}" for i in range(1, 7)]

test_fe["AVG_PAY_RATIO"] = test_fe[ratio_cols].mean(axis=1)

pay_status_cols = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]
test_fe["AVG_PAY_STATUS"] = (
    test_fe[pay_status_cols].mean(axis=1)
)
test_fe["MAX_PAY_STATUS"] = (
    test_fe[pay_status_cols].max(axis=1)
)
test_fe["NUM_DELAY"] = (
    test_fe[pay_status_cols] > 0
).sum(axis=1)

x_test_fe = test_fe.drop(
    columns=["client_id"]
)

In [37]:
logistic_fe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

logistic_fe.fit(x_fe, y_fe)
logistic_fe_prob = logistic_fe.predict_proba(x_test_fe)[:, 1]